export const LendingPoolAbi = 
  [
    {
      inputs: [
        { name: "_collateralToken", internalType: "address", type: "address" },
        { name: "_borrowToken", internalType: "address", type: "address" },
        { name: "_factory", internalType: "address", type: "address" },
        { name: "_ltv", internalType: "uint256", type: "uint256" },
      ],
      stateMutability: "nonpayable",
      type: "constructor",
    },
    { inputs: [], name: "InsufficientBorrowShares", type: "error" },
    { inputs: [], name: "InsufficientCollateral", type: "error" },
    { inputs: [], name: "InsufficientLiquidity", type: "error" },
    { inputs: [], name: "InsufficientShares", type: "error" },
    { inputs: [], name: "LTVExceedMaxAmount", type: "error" },
    { inputs: [], name: "PositionAlreadyCreated", type: "error" },
    { inputs: [], name: "ReentrancyGuardReentrantCall", type: "error" },
    {
      inputs: [{ name: "token", internalType: "address", type: "address" }],
      name: "SafeERC20FailedOperation",
      type: "error",
    },
    { inputs: [], name: "TokenNotAvailable", type: "error" },
    { inputs: [], name: "ZeroAmount", type: "error" },
    { inputs: [], name: "amountSharesInvalid", type: "error" },
    {
      inputs: [
        {
          indexed: false,
          name: "user",
          internalType: "address",
          type: "address",
        },
        {
          indexed: false,
          name: "amount",
          internalType: "uint256",
          type: "uint256",
        },
        {
          indexed: false,
          name: "shares",
          internalType: "uint256",
          type: "uint256",
        },
        {
          indexed: false,
          name: "chainId",
          internalType: "uint256",
          type: "uint256",
        },
        {
          indexed: false,
          name: "bridgeTokenSender",
          internalType: "uint256",
          type: "uint256",
        },
      ],
      name: "BorrowDebtCrosschain",
      anonymous: false,
      type: "event",
    },
    {
      inputs: [
        {
          indexed: false,
          name: "user",
          internalType: "address",
          type: "address",
        },
        {
          indexed: false,
          name: "positionAddress",
          internalType: "address",
          type: "address",
        },
      ],
      name: "CreatePosition",
      anonymous: false,
      type: "event",
    },
    {
      inputs: [
        {
          indexed: false,
          name: "user",
          internalType: "address",
          type: "address",
        },
        {
          indexed: false,
          name: "amount",
          internalType: "uint256",
          type: "uint256",
        },
        {
          indexed: false,
          name: "shares",
          internalType: "uint256",
          type: "uint256",
        },
      ],
      name: "RepayWithCollateralByPosition",
      anonymous: false,
      type: "event",
    },
    {
      inputs: [
        {
          indexed: false,
          name: "user",
          internalType: "address",
          type: "address",
        },
        {
          indexed: false,
          name: "amount",
          internalType: "uint256",
          type: "uint256",
        },
      ],
      name: "SupplyCollateral",
      anonymous: false,
      type: "event",
    },
    {
      inputs: [
        {
          indexed: false,
          name: "user",
          internalType: "address",
          type: "address",
        },
        {
          indexed: false,
          name: "amount",
          internalType: "uint256",
          type: "uint256",
        },
        {
          indexed: false,
          name: "shares",
          internalType: "uint256",
          type: "uint256",
        },
      ],
      name: "SupplyLiquidity",
      anonymous: false,
      type: "event",
    },
    {
      inputs: [
        {
          indexed: false,
          name: "user",
          internalType: "address",
          type: "address",
        },
        {
          indexed: false,
          name: "amount",
          internalType: "uint256",
          type: "uint256",
        },
        {
          indexed: false,
          name: "shares",
          internalType: "uint256",
          type: "uint256",
        },
      ],
      name: "WithdrawLiquidity",
      anonymous: false,
      type: "event",
    },
    {
      outputs: [],
      inputs: [],
      name: "accrueInterest",
      stateMutability: "nonpayable",
      type: "function",
    },
    {
      outputs: [{ name: "", internalType: "address", type: "address" }],
      inputs: [{ name: "", internalType: "address", type: "address" }],
      name: "addressPositions",
      stateMutability: "view",
      type: "function",
    },
    {
      outputs: [],
      inputs: [
        { name: "amount", internalType: "uint256", type: "uint256" },
        { name: "_chainId", internalType: "uint256", type: "uint256" },
        {
          name: "_bridgeTokenSender",
          internalType: "uint256",
          type: "uint256",
        },
      ],
      name: "borrowDebt",
      stateMutability: "payable",
      type: "function",
    },
    {
      outputs: [{ name: "", internalType: "address", type: "address" }],
      inputs: [],
      name: "borrowToken",
      stateMutability: "view",
      type: "function",
    },
    {
      outputs: [{ name: "", internalType: "address", type: "address" }],
      inputs: [],
      name: "collateralToken",
      stateMutability: "view",
      type: "function",
    },
    {
      outputs: [],
      inputs: [],
      name: "createPosition",
      stateMutability: "nonpayable",
      type: "function",
    },
    {
      outputs: [{ name: "", internalType: "address", type: "address" }],
      inputs: [],
      name: "factory",
      stateMutability: "view",
      type: "function",
    },
    {
      outputs: [{ name: "", internalType: "uint256", type: "uint256" }],
      inputs: [],
      name: "lastAccrued",
      stateMutability: "view",
      type: "function",
    },
    {
      outputs: [{ name: "", internalType: "uint256", type: "uint256" }],
      inputs: [],
      name: "ltv",
      stateMutability: "view",
      type: "function",
    },
    {
      outputs: [],
      inputs: [
        { name: "shares", internalType: "uint256", type: "uint256" },
        { name: "_token", internalType: "address", type: "address" },
        { name: "_fromPosition", internalType: "bool", type: "bool" },
      ],
      name: "repayWithSelectedToken",
      stateMutability: "nonpayable",
      type: "function",
    },
    {
      outputs: [],
      inputs: [{ name: "amount", internalType: "uint256", type: "uint256" }],
      name: "supplyCollateral",
      stateMutability: "nonpayable",
      type: "function",
    },
    {
      outputs: [],
      inputs: [{ name: "amount", internalType: "uint256", type: "uint256" }],
      name: "supplyLiquidity",
      stateMutability: "nonpayable",
      type: "function",
    },
    {
      outputs: [
        { name: "amountOut", internalType: "uint256", type: "uint256" },
      ],
      inputs: [
        { name: "_tokenFrom", internalType: "address", type: "address" },
        { name: "_tokenTo", internalType: "address", type: "address" },
        { name: "amountIn", internalType: "uint256", type: "uint256" },
      ],
      name: "swapTokenByPosition",
      stateMutability: "nonpayable",
      type: "function",
    },
    {
      outputs: [{ name: "", internalType: "uint256", type: "uint256" }],
      inputs: [],
      name: "totalBorrowAssets",
      stateMutability: "view",
      type: "function",
    },
    {
      outputs: [{ name: "", internalType: "uint256", type: "uint256" }],
      inputs: [],
      name: "totalBorrowShares",
      stateMutability: "view",
      type: "function",
    },
    {
      outputs: [{ name: "", internalType: "uint256", type: "uint256" }],
      inputs: [],
      name: "totalSupplyAssets",
      stateMutability: "view",
      type: "function",
    },
    {
      outputs: [{ name: "", internalType: "uint256", type: "uint256" }],
      inputs: [],
      name: "totalSupplyShares",
      stateMutability: "view",
      type: "function",
    },
    {
      outputs: [{ name: "", internalType: "uint256", type: "uint256" }],
      inputs: [{ name: "", internalType: "address", type: "address" }],
      name: "userBorrowShares",
      stateMutability: "view",
      type: "function",
    },
    {
      outputs: [{ name: "", internalType: "uint256", type: "uint256" }],
      inputs: [{ name: "", internalType: "address", type: "address" }],
      name: "userSupplyShares",
      stateMutability: "view",
      type: "function",
    },
    {
      outputs: [],
      inputs: [{ name: "amount", internalType: "uint256", type: "uint256" }],
      name: "withdrawCollateral",
      stateMutability: "nonpayable",
      type: "function",
    },
    {
      outputs: [],
      inputs: [{ name: "_shares", internalType: "uint256", type: "uint256" }],
      name: "withdrawLiquidity",
      stateMutability: "nonpayable",
      type: "function",
    },
  ] as const;
